layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: tmscarla
  # instagram: your_username
  # keybase: your_username
  linkedin: tommasoscarlatti
  # mastodon: your_username
  medium: tmscarla
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: tmscarla
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Publications
    web_url: https://github.com/topics/css
    image_url: img/publications.png

  - name: Datashack 2019
    web_url: datashack.html
    image_url: img/polimi_harvard.png

  - name: Spotify RecSys Challenge 2018
    web_url: spotify_recsys.html
    image_url: https://www.freepnglogos.com/uploads/spotify-logo-png/file-spotify-logo-png-4.png

