layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: tommasoscarlatti
  twitter: tmscarla
  hackerrank: tmscarla
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: tmscarla
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  leetcode: tmscarla
  twitch: tmscarla

topics:
  - name: Publications
    web_url: publications
    image_url: img/publications.png

  - name: Slides and Notes
    web_url: slides
    image_url: img/slides.png

  - name: Good Reads
    web_url: good_reads
    image_url: img/books.png
  
  - name: Darione BBQ (2023)
    web_url: darione_bbq
    image_url: img/dbbq_logo.png

  - name: FAWLTS (2020)
    web_url: fawlts
    image_url: img/fawlts_logo.png

  - name: Datashack (2019)
    web_url: datashack
    image_url: img/iacs.png

  - name: Spotify RecSys Challenge (2018)
    web_url: spotify_recsys
    image_url: img/spotify.png

  - name: Tenbuilders (2015)
    web_url: tenbuilders
    image_url: img/tenbuilders.png

  - name: Pocket Maths (2013)
    web_url: pocket_maths
    image_url: img/pocket_maths.png



  

